basePath: /
definitions:
  admin.CreateAdminRequest:
    properties:
      email:
        type: string
    type: object
  pg.Event:
    properties:
      password:
        type: string
      time:
        type: string
      url:
        type: string
    type: object
  url.ShortenRequest:
    properties:
      password:
        type: string
      url:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: a0970785699@gmail.com
    name: Leon Lin
    url: github.com/leon123858
  description: This is a sample in go tutorial for building a short URL service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Simple Short URL API Server
  version: "1.0"
paths:
  /{token}:
    get:
      consumes:
      - application/json
      description: Get the long URL for a given short URL token
      parameters:
      - description: Short URL token
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Redirect to long URL
          schema:
            type: string
        "404":
          description: URL not found
          schema:
            type: string
      summary: Get long URL
      tags:
      - URLs
  /admin/register:
    post:
      consumes:
      - application/json
      description: Create a new admin user with the provided email
      parameters:
      - description: Admin details
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/admin.CreateAdminRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Created admin user
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      summary: Create admin user
      tags:
      - Admin
  /admin/statistic/{password}:
    get:
      consumes:
      - application/json
      description: Get statistics for an admin user with the provided password
      parameters:
      - description: Admin password
        in: path
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Statistics events
          schema:
            items:
              $ref: '#/definitions/pg.Event'
            type: array
        "500":
          description: Internal server error
          schema: {}
      summary: Get admin statistics
      tags:
      - Admin
  /shorten:
    post:
      consumes:
      - application/json
      description: Create a new short URL for a given long URL
      parameters:
      - description: URL to be shortened
        in: body
        name: url
        required: true
        schema:
          $ref: '#/definitions/url.ShortenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Short URL
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Create short URL
      tags:
      - URLs
swagger: "2.0"
